import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'МАТКА',
  description: 'Generated by create next app',
  keywords: 'Next.js, SEO, Web Development, JavaScript, React, App',
  authors: [{ name: 'Your Name', url: 'https://yourwebsite.com' }],
  metadataBase: new URL('https://yourwebsite.com'),
  openGraph: {
    title: 'МАТКА',
    description: 'Generated by create next app',
    url: 'https://yourwebsite.com',
    type: 'website',
    images: [
      {
        url: 'https://yourwebsite.com/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'МАТКА',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    site: '@yourtwitterhandle',
    creator: '@yourtwitterhandle',
    title: 'МАТКА',
    description: 'Generated by create next app',
    images: 'https://yourwebsite.com/twitter-image.jpg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index, follow" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={`${montserrat.variable} antialiased`}>{children}</body>
    </html>
  );
}
